# Server Port 
server:
  port: 8080

# Spring Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/departmentDB

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
