# Server Port
server:
  port: 8081

# Spring Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/employeeDB
  boot:
    message: Hello, Employee Service Spring Cloud Bus Demo

# Register Netflix Eureka Server
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

# Spring Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: "*"
