# Server Port
server:
  port: 8081

# Spring Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/employeeDB
  boot:
    message: Hello, Employee Service Spring Cloud Bus Demo 1

# Register Netflix Eureka Server
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

# Spring Actuator and Zipkin Config
# Actuator endpoints for Circuit Breaker
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state:
          seconds: 5

# Retry Configuration
resilience4j:
  retry:
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 5
        wait-duration:
          seconds: 2s


# Logging Config
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: debug

