# Server Port
server:
  port: 8083

# Spring Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/organizationDB

# Register Netflix Eureka Server
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

# Actuator endpoints for Circuit Breaker
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0


# Logging Config
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: debug
